//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Services.Tests.HistoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Services.Tests.HistoryService.BaseExecutionResultOfHistory3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Services.Tests.HistoryService.HistoryResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfHistory3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Services.Tests.HistoryService.HistoryResult))]
    public partial class BaseExecutionResultOfHistory3XPrIsxh : Personnel.Services.Tests.HistoryService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.History ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.History Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class HistoryResult : Personnel.Services.Tests.HistoryService.BaseExecutionResultOfHistory3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.HistoryUpdateInfo AddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.HistoryUpdateInfo ChangeField;
        
        private long EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.HistoryRemoveInfo RemoveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.HistoryUpdateInfo Add {
            get {
                return this.AddField;
            }
            set {
                if ((object.ReferenceEquals(this.AddField, value) != true)) {
                    this.AddField = value;
                    this.RaisePropertyChanged("Add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.HistoryUpdateInfo Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeField, value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.HistoryRemoveInfo Remove {
            get {
                return this.RemoveField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoveField, value) != true)) {
                    this.RemoveField = value;
                    this.RaisePropertyChanged("Remove");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryUpdateInfo", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class HistoryUpdateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.Appoint[] AppointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.Department[] DepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeeLogin[] EmployeeLoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeePhoto[] EmployeePhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeeRight[] EmployeeRightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.Employee[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.File[] FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.Staffing[] StuffingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.Appoint[] Appoints {
            get {
                return this.AppointsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointsField, value) != true)) {
                    this.AppointsField = value;
                    this.RaisePropertyChanged("Appoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.Department[] Departments {
            get {
                return this.DepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentsField, value) != true)) {
                    this.DepartmentsField = value;
                    this.RaisePropertyChanged("Departments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeeLogin[] EmployeeLogins {
            get {
                return this.EmployeeLoginsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLoginsField, value) != true)) {
                    this.EmployeeLoginsField = value;
                    this.RaisePropertyChanged("EmployeeLogins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeePhoto[] EmployeePhotos {
            get {
                return this.EmployeePhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeePhotosField, value) != true)) {
                    this.EmployeePhotosField = value;
                    this.RaisePropertyChanged("EmployeePhotos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeeRight[] EmployeeRights {
            get {
                return this.EmployeeRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeRightsField, value) != true)) {
                    this.EmployeeRightsField = value;
                    this.RaisePropertyChanged("EmployeeRights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.File[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.Staffing[] Stuffing {
            get {
                return this.StuffingField;
            }
            set {
                if ((object.ReferenceEquals(this.StuffingField, value) != true)) {
                    this.StuffingField = value;
                    this.RaisePropertyChanged("Stuffing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRemoveInfo", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class HistoryRemoveInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] AppointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] DepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] EmployeeLoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] EmployeePhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] EmployeeRightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] StuffingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Appoints {
            get {
                return this.AppointsField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointsField, value) != true)) {
                    this.AppointsField = value;
                    this.RaisePropertyChanged("Appoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Departments {
            get {
                return this.DepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentsField, value) != true)) {
                    this.DepartmentsField = value;
                    this.RaisePropertyChanged("Departments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] EmployeeLogins {
            get {
                return this.EmployeeLoginsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLoginsField, value) != true)) {
                    this.EmployeeLoginsField = value;
                    this.RaisePropertyChanged("EmployeeLogins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] EmployeePhotos {
            get {
                return this.EmployeePhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeePhotosField, value) != true)) {
                    this.EmployeePhotosField = value;
                    this.RaisePropertyChanged("EmployeePhotos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] EmployeeRights {
            get {
                return this.EmployeeRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeRightsField, value) != true)) {
                    this.EmployeeRightsField = value;
                    this.RaisePropertyChanged("EmployeeRights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] Stuffing {
            get {
                return this.StuffingField;
            }
            set {
                if ((object.ReferenceEquals(this.StuffingField, value) != true)) {
                    this.StuffingField = value;
                    this.RaisePropertyChanged("Stuffing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appoint", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Appoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeLogin", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class EmployeeLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeePhoto", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class EmployeePhoto : Personnel.Services.Tests.HistoryService.File {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.PhotoType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.PhotoType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRight", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class EmployeeRight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RightIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RightId {
            get {
                return this.RightIdField;
            }
            set {
                if ((this.RightIdField.Equals(value) != true)) {
                    this.RightIdField = value;
                    this.RaisePropertyChanged("RightId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeeLogin[] LoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeePhoto[] PhotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.EmployeeRight[] RightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Services.Tests.HistoryService.Staffing StuffingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeeLogin[] Logins {
            get {
                return this.LoginsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginsField, value) != true)) {
                    this.LoginsField = value;
                    this.RaisePropertyChanged("Logins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic {
            get {
                return this.PatronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronymicField, value) != true)) {
                    this.PatronymicField = value;
                    this.RaisePropertyChanged("Patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeePhoto[] Photos {
            get {
                return this.PhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotosField, value) != true)) {
                    this.PhotosField = value;
                    this.RaisePropertyChanged("Photos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.EmployeeRight[] Rights {
            get {
                return this.RightsField;
            }
            set {
                if ((object.ReferenceEquals(this.RightsField, value) != true)) {
                    this.RightsField = value;
                    this.RaisePropertyChanged("Rights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Services.Tests.HistoryService.Staffing Stuffing {
            get {
                return this.StuffingField;
            }
            set {
                if ((object.ReferenceEquals(this.StuffingField, value) != true)) {
                    this.StuffingField = value;
                    this.RaisePropertyChanged("Stuffing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Services.Tests.HistoryService.EmployeePhoto))]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewSmallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mime {
            get {
                return this.MimeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeField, value) != true)) {
                    this.MimeField = value;
                    this.RaisePropertyChanged("Mime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview {
            get {
                return this.PreviewField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewField, value) != true)) {
                    this.PreviewField = value;
                    this.RaisePropertyChanged("Preview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewSmall {
            get {
                return this.PreviewSmallField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewSmallField, value) != true)) {
                    this.PreviewSmallField = value;
                    this.RaisePropertyChanged("PreviewSmall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staffing", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Staffing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AppointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AppointId {
            get {
                return this.AppointIdField;
            }
            set {
                if ((this.AppointIdField.Equals(value) != true)) {
                    this.AppointIdField = value;
                    this.RaisePropertyChanged("AppointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoType", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    public enum PhotoType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Full = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar32 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar64 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar128 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar256 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.IHistoryService")]
    public interface IHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Get", ReplyAction="http://tempuri.org/IHistoryService/GetResponse")]
        Personnel.Services.Tests.HistoryService.HistoryResult Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Get", ReplyAction="http://tempuri.org/IHistoryService/GetResponse")]
        System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetFrom", ReplyAction="http://tempuri.org/IHistoryService/GetFromResponse")]
        Personnel.Services.Tests.HistoryService.HistoryResult GetFrom(long eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetFrom", ReplyAction="http://tempuri.org/IHistoryService/GetFromResponse")]
        System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> GetFromAsync(long eventId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoryServiceChannel : Personnel.Services.Tests.HistoryService.IHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoryServiceClient : System.ServiceModel.ClientBase<Personnel.Services.Tests.HistoryService.IHistoryService>, Personnel.Services.Tests.HistoryService.IHistoryService {
        
        public HistoryServiceClient() {
        }
        
        public HistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Services.Tests.HistoryService.HistoryResult Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public Personnel.Services.Tests.HistoryService.HistoryResult GetFrom(long eventId) {
            return base.Channel.GetFrom(eventId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> GetFromAsync(long eventId) {
            return base.Channel.GetFromAsync(eventId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.IHistoryServiceREST")]
    public interface IHistoryServiceREST {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGet", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetResponse")]
        Personnel.Services.Tests.HistoryService.HistoryResult RESTGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGet", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetResponse")]
        System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> RESTGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGetFrom", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetFromResponse")]
        Personnel.Services.Tests.HistoryService.HistoryResult RESTGetFrom(long eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryServiceREST/RESTGetFrom", ReplyAction="http://tempuri.org/IHistoryServiceREST/RESTGetFromResponse")]
        System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> RESTGetFromAsync(long eventId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoryServiceRESTChannel : Personnel.Services.Tests.HistoryService.IHistoryServiceREST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoryServiceRESTClient : System.ServiceModel.ClientBase<Personnel.Services.Tests.HistoryService.IHistoryServiceREST>, Personnel.Services.Tests.HistoryService.IHistoryServiceREST {
        
        public HistoryServiceRESTClient() {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceRESTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceRESTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Services.Tests.HistoryService.HistoryResult RESTGet() {
            return base.Channel.RESTGet();
        }
        
        public System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> RESTGetAsync() {
            return base.Channel.RESTGetAsync();
        }
        
        public Personnel.Services.Tests.HistoryService.HistoryResult RESTGetFrom(long eventId) {
            return base.Channel.RESTGetFrom(eventId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Services.Tests.HistoryService.HistoryResult> RESTGetFromAsync(long eventId) {
            return base.Channel.RESTGetFromAsync(eventId);
        }
    }
}
