//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Repository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personnel.Repository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For type &apos;{0}&apos; rule &apos;one object -&gt; one key&apos; not implemented for &apos;{1}&apos;.
        /// </summary>
        public static string HISTORYRECORD_EntityBreakOntToOneRule {
            get {
                return ResourceManager.GetString("HISTORYRECORD_EntityBreakOntToOneRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint name length must be less or equals 200.
        /// </summary>
        public static string MODEL_APPOINT_NameMaxLength {
            get {
                return ResourceManager.GetString("MODEL_APPOINT_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appoint name required for this item.
        /// </summary>
        public static string MODEL_APPOINT_NameRequired {
            get {
                return ResourceManager.GetString("MODEL_APPOINT_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name length must be less or equals 200.
        /// </summary>
        public static string MODEL_DEPARTMENT_NameMaxLength {
            get {
                return ResourceManager.GetString("MODEL_DEPARTMENT_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name required for this item.
        /// </summary>
        public static string MODEL_DEPARTMENT_NameRequired {
            get {
                return ResourceManager.GetString("MODEL_DEPARTMENT_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee email length must be less or equals 200.
        /// </summary>
        public static string MODEL_EMPLOYEE_EmailMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee name length must be less or equals 50.
        /// </summary>
        public static string MODEL_EMPLOYEE_NameMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required for this item.
        /// </summary>
        public static string MODEL_EMPLOYEE_NameRequired {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee patronymic length must be less or equals 50.
        /// </summary>
        public static string MODEL_EMPLOYEE_PatronymicMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_PatronymicMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee phone length must be less or equals 200.
        /// </summary>
        public static string MODEL_EMPLOYEE_PhoneMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee surname length must be less or equals 50.
        /// </summary>
        public static string MODEL_EMPLOYEE_SurnameMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_SurnameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname required for this item.
        /// </summary>
        public static string MODEL_EMPLOYEE_SurnameRequired {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEE_SurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login max length must be less or equals 100.
        /// </summary>
        public static string MODEL_EMPLOYEELOGIN_LoginMaxLength {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEELOGIN_LoginMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required for this item.
        /// </summary>
        public static string MODEL_EMPLOYEELOGIN_LoginRequired {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEELOGIN_LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar 128x128.
        /// </summary>
        public static string MODEL_EMPLOYEEPHOTOTYPE_Avatar128 {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEEPHOTOTYPE_Avatar128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar 256x256.
        /// </summary>
        public static string MODEL_EMPLOYEEPHOTOTYPE_Avatar256 {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEEPHOTOTYPE_Avatar256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar 32x32.
        /// </summary>
        public static string MODEL_EMPLOYEEPHOTOTYPE_Avatar32 {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEEPHOTOTYPE_Avatar32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar 64x64.
        /// </summary>
        public static string MODEL_EMPLOYEEPHOTOTYPE_Avatar64 {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEEPHOTOTYPE_Avatar64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full photo.
        /// </summary>
        public static string MODEL_EMPLOYEEPHOTOTYPE_Full {
            get {
                return ResourceManager.GetString("MODEL_EMPLOYEEPHOTOTYPE_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find default constructor for type: &apos;{0}&apos;.
        /// </summary>
        public static string MODEL_ENTITYBASE_CanFindDefaultConstructor {
            get {
                return ResourceManager.GetString("MODEL_ENTITYBASE_CanFindDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MODEL_HISTORYCHANGETYPE_Add {
            get {
                return ResourceManager.GetString("MODEL_HISTORYCHANGETYPE_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string MODEL_HISTORYCHANGETYPE_Change {
            get {
                return ResourceManager.GetString("MODEL_HISTORYCHANGETYPE_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MODEL_HISTORYCHANGETYPE_Remove {
            get {
                return ResourceManager.GetString("MODEL_HISTORYCHANGETYPE_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name length must be less or equals 100.
        /// </summary>
        public static string MODEL_RIGHT_SystemNameMaxLength {
            get {
                return ResourceManager.GetString("MODEL_RIGHT_SystemNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name required for this item.
        /// </summary>
        public static string MODEL_RIGHT_SystemNameRequred {
            get {
                return ResourceManager.GetString("MODEL_RIGHT_SystemNameRequred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can login in system (Login).
        /// </summary>
        public static string MODEL_RIGHTTYPE_Login {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage appoints (ManageAppoints).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageAppoints {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageAppoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage departments (ManageDepartments).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageDepartments {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage emplyes logins (ManageEmployeesLogins).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageEmployeesLogins {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageEmployeesLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage employes rights (ManageEmployeesRights).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageEmployeesRights {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageEmployeesRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage employes (ManageEmployes).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageEmployes {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageEmployes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files (ManageFile).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageFile {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage staffing (ManageStaffing).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ManageStaffing {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ManageStaffing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files (UploadFile).
        /// </summary>
        public static string MODEL_RIGHTTYPE_UploadFile {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View changes (ViewChanges).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ViewChanges {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can view employes (ViewEmployes).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ViewEmployes {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ViewEmployes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can view staffing (ViewStaffing).
        /// </summary>
        public static string MODEL_RIGHTTYPE_ViewStaffing {
            get {
                return ResourceManager.GetString("MODEL_RIGHTTYPE_ViewStaffing", resourceCulture);
            }
        }
    }
}
