//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Application.ViewModels.StorageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.BaseExecutionResultOfPicture3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.PictureResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.BaseExecutionResultsOfFile3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.FileResults))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.BaseExecutionResultsOfPicture3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.PictureResults))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.BaseExecutionResultOfFile3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.FileResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfPicture3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.PictureResult))]
    public partial class BaseExecutionResultOfPicture3XPrIsxh : Personnel.Application.ViewModels.StorageService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.Picture ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.Picture Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PictureResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Service.File")]
    [System.SerializableAttribute()]
    public partial class PictureResult : Personnel.Application.ViewModels.StorageService.BaseExecutionResultOfPicture3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultsOfFile3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.FileResults))]
    public partial class BaseExecutionResultsOfFile3XPrIsxh : Personnel.Application.ViewModels.StorageService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.File[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.File[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileResults", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Service.File")]
    [System.SerializableAttribute()]
    public partial class FileResults : Personnel.Application.ViewModels.StorageService.BaseExecutionResultsOfFile3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultsOfPicture3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.PictureResults))]
    public partial class BaseExecutionResultsOfPicture3XPrIsxh : Personnel.Application.ViewModels.StorageService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.Picture[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.Picture[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PictureResults", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Service.File")]
    [System.SerializableAttribute()]
    public partial class PictureResults : Personnel.Application.ViewModels.StorageService.BaseExecutionResultsOfPicture3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfFile3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.StorageService.FileResult))]
    public partial class BaseExecutionResultOfFile3XPrIsxh : Personnel.Application.ViewModels.StorageService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.File ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.File Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Service.File")]
    [System.SerializableAttribute()]
    public partial class FileResult : Personnel.Application.ViewModels.StorageService.BaseExecutionResultOfFile3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviewSmallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mime {
            get {
                return this.MimeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeField, value) != true)) {
                    this.MimeField = value;
                    this.RaisePropertyChanged("Mime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preview {
            get {
                return this.PreviewField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewField, value) != true)) {
                    this.PreviewField = value;
                    this.RaisePropertyChanged("Preview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewSmall {
            get {
                return this.PreviewSmallField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviewSmallField, value) != true)) {
                    this.PreviewSmallField = value;
                    this.RaisePropertyChanged("PreviewSmall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Picture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.File FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.StorageService.PictureType PictureTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.File File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.StorageService.PictureType PictureType {
            get {
                return this.PictureTypeField;
            }
            set {
                if ((this.PictureTypeField.Equals(value) != true)) {
                    this.PictureTypeField = value;
                    this.RaisePropertyChanged("PictureType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PictureType", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    public enum PictureType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar32 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar64 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar128 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avatar256 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.IFileService")]
    public interface IFileService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Get", ReplyAction="http://tempuri.org/IFileService/GetResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult Get(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Get", ReplyAction="http://tempuri.org/IFileService/GetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> GetAsync(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetPicture", ReplyAction="http://tempuri.org/IFileService/GetPictureResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResult GetPicture(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetPicture", ReplyAction="http://tempuri.org/IFileService/GetPictureResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> GetPictureAsync(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFileService/Remove")]
        void Remove(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFileService/Remove")]
        System.Threading.Tasks.Task RemoveAsync(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetRange", ReplyAction="http://tempuri.org/IFileService/GetRangeResponse")]
        Personnel.Application.ViewModels.StorageService.FileResults GetRange(System.Guid[] identifiers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetRange", ReplyAction="http://tempuri.org/IFileService/GetRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResults> GetRangeAsync(System.Guid[] identifiers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetSourceByName", ReplyAction="http://tempuri.org/IFileService/GetSourceByNameResponse")]
        System.IO.Stream GetSourceByName(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetSourceByName", ReplyAction="http://tempuri.org/IFileService/GetSourceByNameResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetSourceByNameAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetSource", ReplyAction="http://tempuri.org/IFileService/GetSourceResponse")]
        System.IO.Stream GetSource(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetSource", ReplyAction="http://tempuri.org/IFileService/GetSourceResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetSourceAsync(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Put", ReplyAction="http://tempuri.org/IFileService/PutResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult Put(System.IO.Stream content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Put", ReplyAction="http://tempuri.org/IFileService/PutResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> PutAsync(System.IO.Stream content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Update", ReplyAction="http://tempuri.org/IFileService/UpdateResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult Update(Personnel.Application.ViewModels.StorageService.File item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/Update", ReplyAction="http://tempuri.org/IFileService/UpdateResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> UpdateAsync(Personnel.Application.ViewModels.StorageService.File item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/FileToPictures", ReplyAction="http://tempuri.org/IFileService/FileToPicturesResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResults FileToPictures(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/FileToPictures", ReplyAction="http://tempuri.org/IFileService/FileToPicturesResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResults> FileToPicturesAsync(System.Guid identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UpdatePicture", ReplyAction="http://tempuri.org/IFileService/UpdatePictureResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResult UpdatePicture(Personnel.Application.ViewModels.StorageService.Picture item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UpdatePicture", ReplyAction="http://tempuri.org/IFileService/UpdatePictureResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> UpdatePictureAsync(Personnel.Application.ViewModels.StorageService.Picture item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : Personnel.Application.ViewModels.StorageService.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<Personnel.Application.ViewModels.StorageService.IFileService>, Personnel.Application.ViewModels.StorageService.IFileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult Get(System.Guid identifier) {
            return base.Channel.Get(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> GetAsync(System.Guid identifier) {
            return base.Channel.GetAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResult GetPicture(System.Guid identifier) {
            return base.Channel.GetPicture(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> GetPictureAsync(System.Guid identifier) {
            return base.Channel.GetPictureAsync(identifier);
        }
        
        public void Remove(System.Guid identifier) {
            base.Channel.Remove(identifier);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(System.Guid identifier) {
            return base.Channel.RemoveAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResults GetRange(System.Guid[] identifiers) {
            return base.Channel.GetRange(identifiers);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResults> GetRangeAsync(System.Guid[] identifiers) {
            return base.Channel.GetRangeAsync(identifiers);
        }
        
        public System.IO.Stream GetSourceByName(string fileName) {
            return base.Channel.GetSourceByName(fileName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetSourceByNameAsync(string fileName) {
            return base.Channel.GetSourceByNameAsync(fileName);
        }
        
        public System.IO.Stream GetSource(System.Guid identifier) {
            return base.Channel.GetSource(identifier);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetSourceAsync(System.Guid identifier) {
            return base.Channel.GetSourceAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult Put(System.IO.Stream content) {
            return base.Channel.Put(content);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> PutAsync(System.IO.Stream content) {
            return base.Channel.PutAsync(content);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult Update(Personnel.Application.ViewModels.StorageService.File item) {
            return base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> UpdateAsync(Personnel.Application.ViewModels.StorageService.File item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResults FileToPictures(System.Guid identifier) {
            return base.Channel.FileToPictures(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResults> FileToPicturesAsync(System.Guid identifier) {
            return base.Channel.FileToPicturesAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResult UpdatePicture(Personnel.Application.ViewModels.StorageService.Picture item) {
            return base.Channel.UpdatePicture(item);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> UpdatePictureAsync(Personnel.Application.ViewModels.StorageService.Picture item) {
            return base.Channel.UpdatePictureAsync(item);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.IFileServiceREST")]
    public interface IFileServiceREST {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGet", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult RESTGet(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGet", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTGetAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetPicture", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetPictureResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResult RESTGetPicture(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetPicture", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetPictureResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> RESTGetPictureAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFileServiceREST/RESTRemove")]
        void RESTRemove(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFileServiceREST/RESTRemove")]
        System.Threading.Tasks.Task RESTRemoveAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetRange", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetRangeResponse")]
        Personnel.Application.ViewModels.StorageService.FileResults RESTGetRange(string[] identifiers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetRange", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResults> RESTGetRangeAsync(string[] identifiers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetSource", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetSourceResponse")]
        System.IO.Stream RESTGetSource(string fileIdOrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTGetSource", ReplyAction="http://tempuri.org/IFileServiceREST/RESTGetSourceResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> RESTGetSourceAsync(string fileIdOrName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTPut", ReplyAction="http://tempuri.org/IFileServiceREST/RESTPutResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult RESTPut(System.IO.Stream content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTPut", ReplyAction="http://tempuri.org/IFileServiceREST/RESTPutResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTPutAsync(System.IO.Stream content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTUpdate", ReplyAction="http://tempuri.org/IFileServiceREST/RESTUpdateResponse")]
        Personnel.Application.ViewModels.StorageService.FileResult RESTUpdate(Personnel.Application.ViewModels.StorageService.File item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTUpdate", ReplyAction="http://tempuri.org/IFileServiceREST/RESTUpdateResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTUpdateAsync(Personnel.Application.ViewModels.StorageService.File item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTFileToPictures", ReplyAction="http://tempuri.org/IFileServiceREST/RESTFileToPicturesResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResults RESTFileToPictures(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTFileToPictures", ReplyAction="http://tempuri.org/IFileServiceREST/RESTFileToPicturesResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResults> RESTFileToPicturesAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTUpdatePicture", ReplyAction="http://tempuri.org/IFileServiceREST/RESTUpdatePictureResponse")]
        Personnel.Application.ViewModels.StorageService.PictureResult RESTUpdatePicture(Personnel.Application.ViewModels.StorageService.Picture item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServiceREST/RESTUpdatePicture", ReplyAction="http://tempuri.org/IFileServiceREST/RESTUpdatePictureResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> RESTUpdatePictureAsync(Personnel.Application.ViewModels.StorageService.Picture item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceRESTChannel : Personnel.Application.ViewModels.StorageService.IFileServiceREST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceRESTClient : System.ServiceModel.ClientBase<Personnel.Application.ViewModels.StorageService.IFileServiceREST>, Personnel.Application.ViewModels.StorageService.IFileServiceREST {
        
        public FileServiceRESTClient() {
        }
        
        public FileServiceRESTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceRESTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceRESTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceRESTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult RESTGet(string identifier) {
            return base.Channel.RESTGet(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTGetAsync(string identifier) {
            return base.Channel.RESTGetAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResult RESTGetPicture(string identifier) {
            return base.Channel.RESTGetPicture(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> RESTGetPictureAsync(string identifier) {
            return base.Channel.RESTGetPictureAsync(identifier);
        }
        
        public void RESTRemove(string identifier) {
            base.Channel.RESTRemove(identifier);
        }
        
        public System.Threading.Tasks.Task RESTRemoveAsync(string identifier) {
            return base.Channel.RESTRemoveAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResults RESTGetRange(string[] identifiers) {
            return base.Channel.RESTGetRange(identifiers);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResults> RESTGetRangeAsync(string[] identifiers) {
            return base.Channel.RESTGetRangeAsync(identifiers);
        }
        
        public System.IO.Stream RESTGetSource(string fileIdOrName) {
            return base.Channel.RESTGetSource(fileIdOrName);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> RESTGetSourceAsync(string fileIdOrName) {
            return base.Channel.RESTGetSourceAsync(fileIdOrName);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult RESTPut(System.IO.Stream content) {
            return base.Channel.RESTPut(content);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTPutAsync(System.IO.Stream content) {
            return base.Channel.RESTPutAsync(content);
        }
        
        public Personnel.Application.ViewModels.StorageService.FileResult RESTUpdate(Personnel.Application.ViewModels.StorageService.File item) {
            return base.Channel.RESTUpdate(item);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.FileResult> RESTUpdateAsync(Personnel.Application.ViewModels.StorageService.File item) {
            return base.Channel.RESTUpdateAsync(item);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResults RESTFileToPictures(string identifier) {
            return base.Channel.RESTFileToPictures(identifier);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResults> RESTFileToPicturesAsync(string identifier) {
            return base.Channel.RESTFileToPicturesAsync(identifier);
        }
        
        public Personnel.Application.ViewModels.StorageService.PictureResult RESTUpdatePicture(Personnel.Application.ViewModels.StorageService.Picture item) {
            return base.Channel.RESTUpdatePicture(item);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.StorageService.PictureResult> RESTUpdatePictureAsync(Personnel.Application.ViewModels.StorageService.Picture item) {
            return base.Channel.RESTUpdatePictureAsync(item);
        }
    }
}
