//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Application.ViewModels.VacationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacationAgreement3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationAgreementResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacationBalance3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationBalanceResults))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacationBalance3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationBalanceResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacation3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationResults))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacation3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacationLevel3XPrIsxh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationLevelResults))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfVacationAgreement3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationAgreementResult))]
    public partial class BaseExecutionResultOfVacationAgreement3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.VacationAgreement ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.VacationAgreement Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationAgreementResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationAgreementResult : Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacationAgreement3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultsOfVacationBalance3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationBalanceResults))]
    public partial class BaseExecutionResultsOfVacationBalance3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.VacationBalance[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.VacationBalance[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationBalanceResults", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationBalanceResults : Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacationBalance3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfVacationBalance3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationBalanceResult))]
    public partial class BaseExecutionResultOfVacationBalance3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.VacationBalance ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.VacationBalance Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationBalanceResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationBalanceResult : Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacationBalance3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultsOfVacation3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationResults))]
    public partial class BaseExecutionResultsOfVacation3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.Vacation[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.Vacation[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationResults", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationResults : Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacation3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultOfVacation3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationResult))]
    public partial class BaseExecutionResultOfVacation3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.Vacation ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.Vacation Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationResult", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationResult : Personnel.Application.ViewModels.VacationService.BaseExecutionResultOfVacation3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseExecutionResultsOfVacationLevel3XPrIsxh", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Personnel.Application.ViewModels.VacationService.VacationLevelResults))]
    public partial class BaseExecutionResultsOfVacationLevel3XPrIsxh : Personnel.Application.ViewModels.VacationService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.VacationLevel[] ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.VacationLevel[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationLevelResults", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationLevelResults : Personnel.Application.ViewModels.VacationService.BaseExecutionResultsOfVacationLevel3XPrIsxh {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationAgreement", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationAgreement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long VacationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VacationId {
            get {
                return this.VacationIdField;
            }
            set {
                if ((this.VacationIdField.Equals(value) != true)) {
                    this.VacationIdField = value;
                    this.RaisePropertyChanged("VacationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationBalance", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationBalance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DayCountAdditionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DayCountMainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DayCountAdditional {
            get {
                return this.DayCountAdditionalField;
            }
            set {
                if ((this.DayCountAdditionalField.Equals(value) != true)) {
                    this.DayCountAdditionalField = value;
                    this.RaisePropertyChanged("DayCountAdditional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DayCountMain {
            get {
                return this.DayCountMainField;
            }
            set {
                if ((this.DayCountMainField.Equals(value) != true)) {
                    this.DayCountMainField = value;
                    this.RaisePropertyChanged("DayCountMain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vacation", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class Vacation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Personnel.Application.ViewModels.VacationService.VacationAgreement[] AgreementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DayCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long VacationLevelIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Personnel.Application.ViewModels.VacationService.VacationAgreement[] Agreements {
            get {
                return this.AgreementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AgreementsField, value) != true)) {
                    this.AgreementsField = value;
                    this.RaisePropertyChanged("Agreements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Begin {
            get {
                return this.BeginField;
            }
            set {
                if ((this.BeginField.Equals(value) != true)) {
                    this.BeginField = value;
                    this.RaisePropertyChanged("Begin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DayCount {
            get {
                return this.DayCountField;
            }
            set {
                if ((this.DayCountField.Equals(value) != true)) {
                    this.DayCountField = value;
                    this.RaisePropertyChanged("DayCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotUsed {
            get {
                return this.NotUsedField;
            }
            set {
                if ((this.NotUsedField.Equals(value) != true)) {
                    this.NotUsedField = value;
                    this.RaisePropertyChanged("NotUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VacationLevelId {
            get {
                return this.VacationLevelIdField;
            }
            set {
                if ((this.VacationLevelIdField.Equals(value) != true)) {
                    this.VacationLevelIdField = value;
                    this.RaisePropertyChanged("VacationLevelId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacationLevel", Namespace="http://schemas.datacontract.org/2004/07/Personnel.Services.Model")]
    [System.SerializableAttribute()]
    public partial class VacationLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName {
            get {
                return this.SystemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemNameField, value) != true)) {
                    this.SystemNameField = value;
                    this.RaisePropertyChanged("SystemName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VacationService.IVacationService")]
    public interface IVacationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementRemove", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementRemoveResponse")]
        Personnel.Application.ViewModels.VacationService.Result VacationAgreementRemove(long vacationAgreementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementRemove", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementRemoveResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationAgreementRemoveAsync(long vacationAgreementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementRemoveRange", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementRemoveRangeResponse")]
        Personnel.Application.ViewModels.VacationService.Result VacationAgreementRemoveRange(long[] vacationAgreementIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementRemoveRange", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementRemoveRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationAgreementRemoveRangeAsync(long[] vacationAgreementIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementInsert", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationAgreementResult VacationAgreementInsert(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementInsert", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> VacationAgreementInsertAsync(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementInsertByUser", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementInsertByUserResponse")]
        Personnel.Application.ViewModels.VacationService.VacationAgreementResult VacationAgreementInsertByUser(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationAgreementInsertByUser", ReplyAction="http://tempuri.org/IVacationService/VacationAgreementInsertByUserResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> VacationAgreementInsertByUserAsync(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationBalanceGet", ReplyAction="http://tempuri.org/IVacationService/VacationBalanceGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationBalanceResults VacationBalanceGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationBalanceGet", ReplyAction="http://tempuri.org/IVacationService/VacationBalanceGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResults> VacationBalanceGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationBalanceInsert", ReplyAction="http://tempuri.org/IVacationService/VacationBalanceInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationBalanceResult VacationBalanceInsert(Personnel.Application.ViewModels.VacationService.VacationBalance vacationBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationBalanceInsert", ReplyAction="http://tempuri.org/IVacationService/VacationBalanceInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResult> VacationBalanceInsertAsync(Personnel.Application.ViewModels.VacationService.VacationBalance vacationBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationsGet", ReplyAction="http://tempuri.org/IVacationService/VacationsGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResults VacationsGet(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationsGet", ReplyAction="http://tempuri.org/IVacationService/VacationsGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResults> VacationsGetAsync(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationGet", ReplyAction="http://tempuri.org/IVacationService/VacationGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult VacationGet(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationGet", ReplyAction="http://tempuri.org/IVacationService/VacationGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationGetAsync(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationRemove", ReplyAction="http://tempuri.org/IVacationService/VacationRemoveResponse")]
        Personnel.Application.ViewModels.VacationService.Result VacationRemove(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationRemove", ReplyAction="http://tempuri.org/IVacationService/VacationRemoveResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationRemoveAsync(long vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationRemoveRange", ReplyAction="http://tempuri.org/IVacationService/VacationRemoveRangeResponse")]
        Personnel.Application.ViewModels.VacationService.Result VacationRemoveRange(long[] vacationIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationRemoveRange", ReplyAction="http://tempuri.org/IVacationService/VacationRemoveRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationRemoveRangeAsync(long[] vacationIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationUpdate", ReplyAction="http://tempuri.org/IVacationService/VacationUpdateResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult VacationUpdate(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationUpdate", ReplyAction="http://tempuri.org/IVacationService/VacationUpdateResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationUpdateAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationInsert", ReplyAction="http://tempuri.org/IVacationService/VacationInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult VacationInsert(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/VacationInsert", ReplyAction="http://tempuri.org/IVacationService/VacationInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/GetLevels", ReplyAction="http://tempuri.org/IVacationService/GetLevelsResponse")]
        Personnel.Application.ViewModels.VacationService.VacationLevelResults GetLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/GetLevels", ReplyAction="http://tempuri.org/IVacationService/GetLevelsResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationLevelResults> GetLevelsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVacationServiceChannel : Personnel.Application.ViewModels.VacationService.IVacationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VacationServiceClient : System.ServiceModel.ClientBase<Personnel.Application.ViewModels.VacationService.IVacationService>, Personnel.Application.ViewModels.VacationService.IVacationService {
        
        public VacationServiceClient() {
        }
        
        public VacationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VacationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result VacationAgreementRemove(long vacationAgreementId) {
            return base.Channel.VacationAgreementRemove(vacationAgreementId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationAgreementRemoveAsync(long vacationAgreementId) {
            return base.Channel.VacationAgreementRemoveAsync(vacationAgreementId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result VacationAgreementRemoveRange(long[] vacationAgreementIds) {
            return base.Channel.VacationAgreementRemoveRange(vacationAgreementIds);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationAgreementRemoveRangeAsync(long[] vacationAgreementIds) {
            return base.Channel.VacationAgreementRemoveRangeAsync(vacationAgreementIds);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationAgreementResult VacationAgreementInsert(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement) {
            return base.Channel.VacationAgreementInsert(vacationAgreement);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> VacationAgreementInsertAsync(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement) {
            return base.Channel.VacationAgreementInsertAsync(vacationAgreement);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationAgreementResult VacationAgreementInsertByUser(long vacationId) {
            return base.Channel.VacationAgreementInsertByUser(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> VacationAgreementInsertByUserAsync(long vacationId) {
            return base.Channel.VacationAgreementInsertByUserAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationBalanceResults VacationBalanceGet() {
            return base.Channel.VacationBalanceGet();
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResults> VacationBalanceGetAsync() {
            return base.Channel.VacationBalanceGetAsync();
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationBalanceResult VacationBalanceInsert(Personnel.Application.ViewModels.VacationService.VacationBalance vacationBalance) {
            return base.Channel.VacationBalanceInsert(vacationBalance);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResult> VacationBalanceInsertAsync(Personnel.Application.ViewModels.VacationService.VacationBalance vacationBalance) {
            return base.Channel.VacationBalanceInsertAsync(vacationBalance);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResults VacationsGet(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to) {
            return base.Channel.VacationsGet(from, to);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResults> VacationsGetAsync(System.Nullable<System.DateTime> from, System.Nullable<System.DateTime> to) {
            return base.Channel.VacationsGetAsync(from, to);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult VacationGet(long vacationId) {
            return base.Channel.VacationGet(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationGetAsync(long vacationId) {
            return base.Channel.VacationGetAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result VacationRemove(long vacationId) {
            return base.Channel.VacationRemove(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationRemoveAsync(long vacationId) {
            return base.Channel.VacationRemoveAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result VacationRemoveRange(long[] vacationIds) {
            return base.Channel.VacationRemoveRange(vacationIds);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> VacationRemoveRangeAsync(long[] vacationIds) {
            return base.Channel.VacationRemoveRangeAsync(vacationIds);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult VacationUpdate(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.VacationUpdate(vacation);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationUpdateAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.VacationUpdateAsync(vacation);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult VacationInsert(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.VacationInsert(vacation);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> VacationInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.VacationInsertAsync(vacation);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationLevelResults GetLevels() {
            return base.Channel.GetLevels();
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationLevelResults> GetLevelsAsync() {
            return base.Channel.GetLevelsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VacationService.IVacationServiceREST")]
    public interface IVacationServiceREST {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        void ChangeLanguage(string codename);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBaseService/ChangeLanguage")]
        System.Threading.Tasks.Task ChangeLanguageAsync(string codename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemove", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveResponse")]
        Personnel.Application.ViewModels.VacationService.Result RESTVacationAgreementRemove(string vacationAgreementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemove", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationAgreementRemoveAsync(string vacationAgreementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveRange", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveRangeResponse")]
        Personnel.Application.ViewModels.VacationService.Result RESTVacationAgreementRemoveRange(string[] vacationAgreementIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveRange", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementRemoveRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationAgreementRemoveRangeAsync(string[] vacationAgreementIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationAgreementResult RESTVacationAgreementInsert(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> RESTVacationAgreementInsertAsync(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertByUser", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertByUserResponse" +
            "")]
        Personnel.Application.ViewModels.VacationService.VacationAgreementResult RESTVacationAgreementInsertByUser(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertByUser", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationAgreementInsertByUserResponse" +
            "")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> RESTVacationAgreementInsertByUserAsync(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationBalanceResults RESTVacationBalanceGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResults> RESTVacationBalanceGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationBalanceResult RESTVacationBalanceInsert(Personnel.Application.ViewModels.VacationService.Vacation vacationBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationBalanceInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResult> RESTVacationBalanceInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacationBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationsGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationsGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResults RESTVacationsGet(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationsGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationsGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResults> RESTVacationsGetAsync(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationGetResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationGet(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationGet", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationGetResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationGetAsync(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationRemove", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveResponse")]
        Personnel.Application.ViewModels.VacationService.Result RESTVacationRemove(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationRemove", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationRemoveAsync(string vacationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveRange", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveRangeResponse")]
        Personnel.Application.ViewModels.VacationService.Result RESTVacationRemoveRange(string[] vacationIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveRange", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationRemoveRangeResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationRemoveRangeAsync(string[] vacationIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationUpdate", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationUpdateResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationUpdate(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationUpdate", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationUpdateResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationUpdateAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationInsertResponse")]
        Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationInsert(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTVacationInsert", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTVacationInsertResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTGetLevels", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTGetLevelsResponse")]
        Personnel.Application.ViewModels.VacationService.VacationLevelResults RESTGetLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationServiceREST/RESTGetLevels", ReplyAction="http://tempuri.org/IVacationServiceREST/RESTGetLevelsResponse")]
        System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationLevelResults> RESTGetLevelsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVacationServiceRESTChannel : Personnel.Application.ViewModels.VacationService.IVacationServiceREST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VacationServiceRESTClient : System.ServiceModel.ClientBase<Personnel.Application.ViewModels.VacationService.IVacationServiceREST>, Personnel.Application.ViewModels.VacationService.IVacationServiceREST {
        
        public VacationServiceRESTClient() {
        }
        
        public VacationServiceRESTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VacationServiceRESTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceRESTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceRESTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ChangeLanguage(string codename) {
            base.Channel.ChangeLanguage(codename);
        }
        
        public System.Threading.Tasks.Task ChangeLanguageAsync(string codename) {
            return base.Channel.ChangeLanguageAsync(codename);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result RESTVacationAgreementRemove(string vacationAgreementId) {
            return base.Channel.RESTVacationAgreementRemove(vacationAgreementId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationAgreementRemoveAsync(string vacationAgreementId) {
            return base.Channel.RESTVacationAgreementRemoveAsync(vacationAgreementId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result RESTVacationAgreementRemoveRange(string[] vacationAgreementIds) {
            return base.Channel.RESTVacationAgreementRemoveRange(vacationAgreementIds);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationAgreementRemoveRangeAsync(string[] vacationAgreementIds) {
            return base.Channel.RESTVacationAgreementRemoveRangeAsync(vacationAgreementIds);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationAgreementResult RESTVacationAgreementInsert(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement) {
            return base.Channel.RESTVacationAgreementInsert(vacationAgreement);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> RESTVacationAgreementInsertAsync(Personnel.Application.ViewModels.VacationService.VacationAgreement vacationAgreement) {
            return base.Channel.RESTVacationAgreementInsertAsync(vacationAgreement);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationAgreementResult RESTVacationAgreementInsertByUser(string vacationId) {
            return base.Channel.RESTVacationAgreementInsertByUser(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationAgreementResult> RESTVacationAgreementInsertByUserAsync(string vacationId) {
            return base.Channel.RESTVacationAgreementInsertByUserAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationBalanceResults RESTVacationBalanceGet() {
            return base.Channel.RESTVacationBalanceGet();
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResults> RESTVacationBalanceGetAsync() {
            return base.Channel.RESTVacationBalanceGetAsync();
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationBalanceResult RESTVacationBalanceInsert(Personnel.Application.ViewModels.VacationService.Vacation vacationBalance) {
            return base.Channel.RESTVacationBalanceInsert(vacationBalance);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationBalanceResult> RESTVacationBalanceInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacationBalance) {
            return base.Channel.RESTVacationBalanceInsertAsync(vacationBalance);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResults RESTVacationsGet(string from, string to) {
            return base.Channel.RESTVacationsGet(from, to);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResults> RESTVacationsGetAsync(string from, string to) {
            return base.Channel.RESTVacationsGetAsync(from, to);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationGet(string vacationId) {
            return base.Channel.RESTVacationGet(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationGetAsync(string vacationId) {
            return base.Channel.RESTVacationGetAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result RESTVacationRemove(string vacationId) {
            return base.Channel.RESTVacationRemove(vacationId);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationRemoveAsync(string vacationId) {
            return base.Channel.RESTVacationRemoveAsync(vacationId);
        }
        
        public Personnel.Application.ViewModels.VacationService.Result RESTVacationRemoveRange(string[] vacationIds) {
            return base.Channel.RESTVacationRemoveRange(vacationIds);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.Result> RESTVacationRemoveRangeAsync(string[] vacationIds) {
            return base.Channel.RESTVacationRemoveRangeAsync(vacationIds);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationUpdate(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.RESTVacationUpdate(vacation);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationUpdateAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.RESTVacationUpdateAsync(vacation);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationResult RESTVacationInsert(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.RESTVacationInsert(vacation);
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationResult> RESTVacationInsertAsync(Personnel.Application.ViewModels.VacationService.Vacation vacation) {
            return base.Channel.RESTVacationInsertAsync(vacation);
        }
        
        public Personnel.Application.ViewModels.VacationService.VacationLevelResults RESTGetLevels() {
            return base.Channel.RESTGetLevels();
        }
        
        public System.Threading.Tasks.Task<Personnel.Application.ViewModels.VacationService.VacationLevelResults> RESTGetLevelsAsync() {
            return base.Channel.RESTGetLevelsAsync();
        }
    }
}
