//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Application.ViewModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personnel.Application.ViewModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New department.
        /// </summary>
        internal static string DEPARTMENTEDIT_NewDepartmentName {
            get {
                return ResourceManager.GetString("DEPARTMENTEDIT_NewDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        internal static string LOADED {
            get {
                return ResourceManager.GetString("LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NOTIFICATION {
            get {
                return ResourceManager.GetString("NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string STARTED {
            get {
                return ResourceManager.GetString("STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoped.
        /// </summary>
        internal static string STOPED {
            get {
                return ResourceManager.GetString("STOPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded.
        /// </summary>
        internal static string UNLOADED {
            get {
                return ResourceManager.GetString("UNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By day.
        /// </summary>
        internal static string VMBIRTHDAYS_BYDAY {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_BYDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By month.
        /// </summary>
        internal static string VMBIRTHDAYS_BYMONTH {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_BYMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By week.
        /// </summary>
        internal static string VMBIRTHDAYS_BYWEEK {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_BYWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By year.
        /// </summary>
        internal static string VMBIRTHDAYS_BYYEAR {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_BYYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string VMBIRTHDAYS_DAY {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string VMBIRTHDAYS_WEEK {
            get {
                return ResourceManager.GetString("VMBIRTHDAYS_WEEK", resourceCulture);
            }
        }
    }
}
